/*******************************************************************************
* Copyright (C) 2019-2022 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// intelnet
// This file was @generated by ai8xize.py --test-dir synthed_net --prefix intelnet --checkpoint-file trained/intel_trained-q.pth.tar --config-file networks/intelnet.yaml --sample-input tests/sample_intel.npy --softmax --device MAX78000 --compact-data --mexpress --timer 0 --display-checkpoint --verbose --overwrite

// DO NOT EDIT - regenerate this file instead!

// Configuring 8 layers
// Input data: HWC
// Layer 0: 3x64x64, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 0/0, ReLU, 32x62x62 output
// Layer 1: 32x62x62, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 0/0, ReLU, 64x29x29 output
// Layer 2: 64x29x29, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 16x29x29 output
// Layer 3: 64x29x29, no pooling, conv2d with kernel size 1x1, stride 1/1, pad 0/0, ReLU, 16x29x29 output
// Layer 4: 32x29x29, max pool 2x2 with stride 2/2, conv2d with kernel size 3x3, stride 1/1, pad 0/0, ReLU, 16x12x12 output
// Layer 5: 16x12x12, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 0/0, ReLU, 8x10x10 output
// Layer 6: 8x10x10 flattened to 800x1x1, no pooling, linear, ReLU, 32x1x1 output
// Layer 7: 32x1x1, no pooling, linear, no activation, 6x1x1 output

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

static const uint8_t bias_0[] = BIAS_0;
static const uint8_t bias_1[] = BIAS_1;
static const uint8_t bias_2[] = BIAS_2;
static const uint8_t bias_3[] = BIAS_3;

static void memcpy_8to32(uint32_t *dst, const uint8_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

int cnn_load_bias(void)
{
  memcpy_8to32((uint32_t *) 0x50108000, bias_0, sizeof(uint8_t) * 48);
  memcpy_8to32((uint32_t *) 0x50508000, bias_1, sizeof(uint8_t) * 64);
  memcpy_8to32((uint32_t *) 0x50908000, bias_2, sizeof(uint8_t) * 40);
  memcpy_8to32((uint32_t *) 0x50d08000, bias_3, sizeof(uint8_t) * 38);

  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50100008) = 0x00000007; // Layer count
  *((volatile uint32_t *) 0x50500000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500008) = 0x00000007; // Layer count
  *((volatile uint32_t *) 0x50900000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900008) = 0x00000007; // Layer count
  *((volatile uint32_t *) 0x50d00000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00008) = 0x00000007; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100010) = 0x0000003f; // Rows
  *((volatile uint32_t *) 0x50100090) = 0x0000003f; // Columns
  *((volatile uint32_t *) 0x50100310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100590) = 0x00004b20; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0x000000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100690) = 0x0000003d; // TRAM ptr max
  *((volatile uint32_t *) 0x50100710) = 0x00070007; // Mask and processor enables

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500010) = 0x0000003f; // Rows
  *((volatile uint32_t *) 0x50500090) = 0x0000003f; // Columns
  *((volatile uint32_t *) 0x50500310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0x000000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500690) = 0x0000003d; // TRAM ptr max

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900010) = 0x0000003f; // Rows
  *((volatile uint32_t *) 0x50900090) = 0x0000003f; // Columns
  *((volatile uint32_t *) 0x50900310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0x000000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900690) = 0x0000003d; // TRAM ptr max
  *((volatile uint32_t *) 0x50900790) = 0x00001000; // Post processing register

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00010) = 0x0000003f; // Rows
  *((volatile uint32_t *) 0x50d00090) = 0x0000003f; // Columns
  *((volatile uint32_t *) 0x50d00310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0x000000f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00690) = 0x0000003d; // TRAM ptr max

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x50100014) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x50100094) = 0x0000003d; // Columns
  *((volatile uint32_t *) 0x50100194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50100294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100514) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50100594) = 0x00002ba0; // Layer control
  *((volatile uint32_t *) 0x50100a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100614) = 0x010002f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100694) = 0x0000001c; // TRAM ptr max
  *((volatile uint32_t *) 0x50100714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x50500014) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x50500094) = 0x0000003d; // Columns
  *((volatile uint32_t *) 0x50500194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50500294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500514) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50500594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500614) = 0x010002f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500694) = 0x0000001c; // TRAM ptr max
  *((volatile uint32_t *) 0x50500794) = 0x00001000; // Post processing register
  *((volatile uint32_t *) 0x50500714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x50900014) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x50900094) = 0x0000003d; // Columns
  *((volatile uint32_t *) 0x50900194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50900294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900514) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50900594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900614) = 0x010002f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900694) = 0x0000001c; // TRAM ptr max

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x50d00014) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x50d00094) = 0x0000003d; // Columns
  *((volatile uint32_t *) 0x50d00194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00214) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d00294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00514) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00614) = 0x010002f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00694) = 0x0000001c; // TRAM ptr max

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x50100018) = 0x0001001e; // Rows
  *((volatile uint32_t *) 0x50100098) = 0x0001001e; // Columns
  *((volatile uint32_t *) 0x50100318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100598) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a18) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100618) = 0x03000378; // Mask offset and count
  *((volatile uint32_t *) 0x50100698) = 0x0000001c; // TRAM ptr max
  *((volatile uint32_t *) 0x50100718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x50500018) = 0x0001001e; // Rows
  *((volatile uint32_t *) 0x50500098) = 0x0001001e; // Columns
  *((volatile uint32_t *) 0x50500318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a18) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500618) = 0x03000378; // Mask offset and count
  *((volatile uint32_t *) 0x50500698) = 0x0000001c; // TRAM ptr max
  *((volatile uint32_t *) 0x50500718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x50900018) = 0x0001001e; // Rows
  *((volatile uint32_t *) 0x50900098) = 0x0001001e; // Columns
  *((volatile uint32_t *) 0x50900318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a18) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900618) = 0x03000378; // Mask offset and count
  *((volatile uint32_t *) 0x50900698) = 0x0000001c; // TRAM ptr max
  *((volatile uint32_t *) 0x50900718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x50d00018) = 0x0001001e; // Rows
  *((volatile uint32_t *) 0x50d00098) = 0x0001001e; // Columns
  *((volatile uint32_t *) 0x50d00318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a18) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00618) = 0x03000378; // Mask offset and count
  *((volatile uint32_t *) 0x50d00698) = 0x0000001c; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00798) = 0x00001000; // Post processing register
  *((volatile uint32_t *) 0x50d00718) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x5010001c) = 0x0000001c; // Rows
  *((volatile uint32_t *) 0x5010009c) = 0x0000001c; // Columns
  *((volatile uint32_t *) 0x5010031c) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x5010039c) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010059c) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5010061c) = 0x1f801ff8; // Mask offset and count
  *((volatile uint32_t *) 0x5010011c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x5010071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x5050001c) = 0x0000001c; // Rows
  *((volatile uint32_t *) 0x5050009c) = 0x0000001c; // Columns
  *((volatile uint32_t *) 0x5050031c) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x5050039c) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5050061c) = 0x1f801ff8; // Mask offset and count
  *((volatile uint32_t *) 0x5050011c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x5050071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x5090001c) = 0x0000001c; // Rows
  *((volatile uint32_t *) 0x5090009c) = 0x0000001c; // Columns
  *((volatile uint32_t *) 0x5090031c) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x5090039c) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5090061c) = 0x1f801ff8; // Mask offset and count
  *((volatile uint32_t *) 0x5090011c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x5090071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x50d0001c) = 0x0000001c; // Rows
  *((volatile uint32_t *) 0x50d0009c) = 0x0000001c; // Columns
  *((volatile uint32_t *) 0x50d0031c) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0039c) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d0061c) = 0x1f801ff8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0011c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d0079c) = 0x00001010; // Post processing register
  *((volatile uint32_t *) 0x50d0071c) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 0
  *((volatile uint32_t *) 0x50100020) = 0x0000001c; // Rows
  *((volatile uint32_t *) 0x501000a0) = 0x0000001c; // Columns
  *((volatile uint32_t *) 0x501001a0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100220) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x501002a0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100320) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100520) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a0) = 0x00002ba0; // Layer control
  *((volatile uint32_t *) 0x50100a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100620) = 0x03a00418; // Mask offset and count
  *((volatile uint32_t *) 0x501006a0) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a0) = 0x00001020; // Post processing register
  *((volatile uint32_t *) 0x50100720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 1
  *((volatile uint32_t *) 0x50500020) = 0x0000001c; // Rows
  *((volatile uint32_t *) 0x505000a0) = 0x0000001c; // Columns
  *((volatile uint32_t *) 0x505001a0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500220) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x505002a0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500320) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500520) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500620) = 0x03a00418; // Mask offset and count
  *((volatile uint32_t *) 0x505006a0) = 0x0000000b; // TRAM ptr max
  *((volatile uint32_t *) 0x50500720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 2
  *((volatile uint32_t *) 0x50900020) = 0x0000001c; // Rows
  *((volatile uint32_t *) 0x509000a0) = 0x0000001c; // Columns
  *((volatile uint32_t *) 0x509001a0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900220) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x509002a0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900320) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900520) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900620) = 0x03a00418; // Mask offset and count
  *((volatile uint32_t *) 0x509006a0) = 0x0000000b; // TRAM ptr max

  // Layer 4 quadrant 3
  *((volatile uint32_t *) 0x50d00020) = 0x0000001c; // Rows
  *((volatile uint32_t *) 0x50d000a0) = 0x0000001c; // Columns
  *((volatile uint32_t *) 0x50d001a0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00220) = 0x00000001; // Pooling columns
  *((volatile uint32_t *) 0x50d002a0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00320) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00520) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a0) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00620) = 0x03a00418; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a0) = 0x0000000b; // TRAM ptr max

  // Layer 5 quadrant 0
  *((volatile uint32_t *) 0x50100024) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x501000a4) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a4) = 0x0000cb20; // Layer control
  *((volatile uint32_t *) 0x50100a24) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50100624) = 0x00000038; // Mask offset and count
  *((volatile uint32_t *) 0x501006a4) = 0x00000009; // TRAM ptr max

  // Layer 5 quadrant 1
  *((volatile uint32_t *) 0x50500024) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x505000a4) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a24) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50500624) = 0x00000038; // Mask offset and count
  *((volatile uint32_t *) 0x505006a4) = 0x00000009; // TRAM ptr max

  // Layer 5 quadrant 2
  *((volatile uint32_t *) 0x50900024) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x509000a4) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a24) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50900624) = 0x00000038; // Mask offset and count
  *((volatile uint32_t *) 0x509006a4) = 0x00000009; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a4) = 0x00001020; // Post processing register

  // Layer 5 quadrant 3
  *((volatile uint32_t *) 0x50d00024) = 0x0000000b; // Rows
  *((volatile uint32_t *) 0x50d000a4) = 0x0000000b; // Columns
  *((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a24) = 0x00003800; // Layer control 2
  *((volatile uint32_t *) 0x50d00624) = 0x00000038; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a4) = 0x00000009; // TRAM ptr max
  *((volatile uint32_t *) 0x50d00724) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 0
  *((volatile uint32_t *) 0x50100328) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003a8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a28) = 0x0000f803; // Layer control 2
  *((volatile uint32_t *) 0x50100628) = 0x25208918; // Mask offset and count
  *((volatile uint32_t *) 0x50100128) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501006a8) = 0x006300c7; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a8) = 0x08181000; // Post processing register
  *((volatile uint32_t *) 0x50100728) = 0x00ff00ff; // Mask and processor enables

  // Layer 6 quadrant 1
  *((volatile uint32_t *) 0x50500328) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003a8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a28) = 0x0000f803; // Layer control 2
  *((volatile uint32_t *) 0x50500628) = 0x25208918; // Mask offset and count
  *((volatile uint32_t *) 0x50500128) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505006a8) = 0x006300c7; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a8) = 0x08180000; // Post processing register

  // Layer 6 quadrant 2
  *((volatile uint32_t *) 0x50900328) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003a8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a28) = 0x0000f803; // Layer control 2
  *((volatile uint32_t *) 0x50900628) = 0x25208918; // Mask offset and count
  *((volatile uint32_t *) 0x50900128) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509006a8) = 0x006300c7; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a8) = 0x08180000; // Post processing register

  // Layer 6 quadrant 3
  *((volatile uint32_t *) 0x50d00328) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003a8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a28) = 0x0000f803; // Layer control 2
  *((volatile uint32_t *) 0x50d00628) = 0x25208918; // Mask offset and count
  *((volatile uint32_t *) 0x50d00128) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d006a8) = 0x006300c7; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a8) = 0x08180000; // Post processing register

  // Layer 7 quadrant 0
  *((volatile uint32_t *) 0x5010032c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x501003ac) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005ac) = 0x0001c920; // Layer control
  *((volatile uint32_t *) 0x50100a2c) = 0x00002800; // Layer control 2
  *((volatile uint32_t *) 0x5010062c) = 0x02400268; // Mask offset and count
  *((volatile uint32_t *) 0x5010012c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007ac) = 0x00006000; // Post processing register

  // Layer 7 quadrant 1
  *((volatile uint32_t *) 0x5050032c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x505003ac) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005ac) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50500a2c) = 0x00002800; // Layer control 2
  *((volatile uint32_t *) 0x5050062c) = 0x02400268; // Mask offset and count
  *((volatile uint32_t *) 0x5050012c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007ac) = 0x00006000; // Post processing register

  // Layer 7 quadrant 2
  *((volatile uint32_t *) 0x5090032c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x509003ac) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005ac) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50900a2c) = 0x00002800; // Layer control 2
  *((volatile uint32_t *) 0x5090062c) = 0x02400268; // Mask offset and count
  *((volatile uint32_t *) 0x5090012c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007ac) = 0x00006000; // Post processing register
  *((volatile uint32_t *) 0x5090072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 3
  *((volatile uint32_t *) 0x50d0032c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003ac) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005ac) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50d00a2c) = 0x00002800; // Layer control 2
  *((volatile uint32_t *) 0x50d0062c) = 0x02400268; // Mask offset and count
  *((volatile uint32_t *) 0x50d0012c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007ac) = 0x00007020; // Post processing register
  *((volatile uint32_t *) 0x50d0072c) = 0xffffffff; // Mask and processor enables


  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x50100000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf)
{
  volatile uint32_t *addr;

  // Custom unload for this network, layer 7 (Linear2): 32-bit data, shape: (6, 1, 1)
  addr = (volatile uint32_t *) 0x50402000;
  *out_buf++ = *addr++;
  *out_buf++ = *addr++;
  *out_buf++ = *addr++;
  *out_buf++ = *addr++;
  addr = (volatile uint32_t *) 0x5040a000;
  *out_buf++ = *addr++;
  *out_buf++ = *addr++;

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

